name: main

on:
  push:
    branches:
      - "**"  
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.9
      - name: install dependencies
        run: pip install .
      - name: lint
        uses: wearerequired/lint-action@v2
        with:
          continue_on_error: false
          black: true
          flake8: true
  bandit:
    name: bandit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.9
      - name: install dependencies
        run: pip install .
      - name: bandit
        run: bandit -r -c pyproject.toml .
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.9
      - name: install dependencies
        run: pip install .
      - name: isort
        uses: isort/isort-action@v1.1.0
  test:
    name: test
    runs-on: ubuntu-latest
    needs: [lint, bandit, isort]
    steps:
      - uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.9
      - name: install dependencies
        run: pip install .
      - name: test
        run: python -m pytest
  tag:
    name: tag version
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: version and tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
